[0m17:20:01.967463 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10886d940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109cc3ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109cc3d90>]}


============================== 17:20:01.970471 | e6217e48-b1b5-4c2a-96be-b85e7f7b8dcd ==============================
[0m17:20:01.970471 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:20:01.970819 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/simgecetin/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init my_dbt_billing_project', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:20:01.979533 [debug] [MainThread]: Starter project path: /Users/simgecetin/simgedbt/Personio/my_dbt_billing_project/venv/lib/python3.13/site-packages/dbt/include/starter_project
[0m17:20:01.999662 [info ] [MainThread]: 
Your new dbt project "my_dbt_billing_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:20:01.999932 [info ] [MainThread]: Setting up your profile.
[0m17:20:02.001679 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m17:20:02.003066 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 0.08397242, "process_in_blocks": "0", "process_kernel_time": 0.147483, "process_mem_max_rss": "100171776", "process_out_blocks": "0", "process_user_time": 0.689046}
[0m17:20:02.003398 [debug] [MainThread]: Command `dbt init` failed at 17:20:02.003333 after 0.08 seconds
[0m17:20:02.003620 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109d94b00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109d7b2f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109c516a0>]}
[0m17:20:02.003846 [debug] [MainThread]: Flushing usage events
[0m17:20:02.433723 [debug] [MainThread]: An error was encountered while trying to flush usage events
